"""Update message model and conversation model

Revision ID: 53b438fc023b
Revises: cf680b6320d2
Create Date: 2025-11-17 21:58:20.486979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53b438fc023b'
down_revision: Union[str, Sequence[str], None] = 'cf680b6320d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.drop_table('invites')
    op.add_column('conversations', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('conversations', sa.Column('source_id', sa.Uuid(), nullable=True))
    op.add_column('conversations', sa.Column('is_imported', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('messages', sa.Column('source_id', sa.Uuid(), nullable=True))
    op.add_column('messages', sa.Column('is_imported', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_imported')
    op.drop_column('messages', 'source_id')
    op.drop_column('messages', 'source')
    op.drop_column('conversations', 'is_imported')
    op.drop_column('conversations', 'source_id')
    op.drop_column('conversations', 'source')
    op.create_table('invites',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('used_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('invites_pkey'))
    )
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=True)
    # ### end Alembic commands ###
