"""Add is favorite to vacancies

Revision ID: 6dcd7e3425e8
Revises: 3909ac0cf04f
Create Date: 2026-01-21 00:42:27.921795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dcd7e3425e8'
down_revision: Union[str, Sequence[str], None] = '3909ac0cf04f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем колонку со значением по умолчанию для существующих записей
    op.add_column('vacancies', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_vacancies_is_favorite'), 'vacancies', ['is_favorite'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_is_favorite'), table_name='vacancies')
    op.drop_column('vacancies', 'is_favorite')
    # ### end Alembic commands ###
