"""add documents table

Revision ID: a63999dc73b6
Revises: b443eff556e9
Create Date: 2026-02-17 14:20:52.612931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a63999dc73b6'
down_revision: Union[str, Sequence[str], None] = 'b443eff556e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('NOTE', 'DOCUMENT', 'PLAN', 'CODE', 'RESEARCH', 'SUMMARY', 'TEMPLATE', name='documentcategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('qdrant_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_conversation', 'documents', ['conversation_id'], unique=False)
    op.create_index('ix_documents_pagination', 'documents', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_documents_tags', 'documents', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_user_documents_user_category', 'documents', ['user_id', 'category'], unique=False)
    op.create_index('ix_user_documents_user_id', 'documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_documents_user_id', table_name='documents')
    op.drop_index('ix_user_documents_user_category', table_name='documents')
    op.drop_index('ix_documents_tags', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_documents_pagination', table_name='documents')
    op.drop_index('ix_documents_conversation', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
