"""add vacancy_analyses table

Revision ID: 29d34e1f6384
Revises: 6dcd7e3425e8
Create Date: 2026-01-21 18:04:13.057510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29d34e1f6384'
down_revision: Union[str, Sequence[str], None] = '6dcd7e3425e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_template', sa.String(length=100), nullable=True),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('result_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_analyses_analysis_type'), 'vacancy_analyses', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_vacancy_analyses_created_at'), 'vacancy_analyses', ['created_at'], unique=False)
    op.create_index('ix_vacancy_analyses_pagination_created', 'vacancy_analyses', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_vacancy_analyses_user_created', 'vacancy_analyses', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_vacancy_analyses_vacancy_id'), 'vacancy_analyses', ['vacancy_id'], unique=False)
    op.create_index('ix_vacancy_analyses_vacancy_type_created', 'vacancy_analyses', ['vacancy_id', 'analysis_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vacancy_analyses_vacancy_type_created', table_name='vacancy_analyses')
    op.drop_index(op.f('ix_vacancy_analyses_vacancy_id'), table_name='vacancy_analyses')
    op.drop_index('ix_vacancy_analyses_user_created', table_name='vacancy_analyses')
    op.drop_index('ix_vacancy_analyses_pagination_created', table_name='vacancy_analyses')
    op.drop_index(op.f('ix_vacancy_analyses_created_at'), table_name='vacancy_analyses')
    op.drop_index(op.f('ix_vacancy_analyses_analysis_type'), table_name='vacancy_analyses')
    op.drop_table('vacancy_analyses')
    # ### end Alembic commands ###
