"""add resume field to users

Revision ID: eb36ad583fa0
Revises: 29d34e1f6384
Create Date: 2026-01-21 23:21:21.698565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb36ad583fa0'
down_revision: Union[str, Sequence[str], None] = '29d34e1f6384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume')
    # ### end Alembic commands ###
