"""add_user_vacancies_many_to_many

Revision ID: 12cb275a7ea3
Revises: 50dc154c0782
Create Date: 2026-01-31 20:24:06.681558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12cb275a7ea3'
down_revision: Union[str, Sequence[str], None] = '50dc154c0782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_vacancies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vacancy_id', name='uq_user_vacancy')
    )
    op.create_index('ix_user_vacancies_favorite', 'user_vacancies', ['user_id', 'is_favorite'], unique=False)
    op.create_index('ix_user_vacancies_user_id', 'user_vacancies', ['user_id'], unique=False)
    op.create_index('ix_user_vacancies_vacancy_id', 'user_vacancies', ['vacancy_id'], unique=False)
    op.execute("""
        INSERT INTO user_vacancies (id, user_id, vacancy_id, is_favorite, created_at)
        SELECT gen_random_uuid(), user_id, id, is_favorite, created_at
        FROM vacancies
    """)
    op.drop_index(op.f('ix_vacancies_is_favorite'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_pagination_created'), table_name='vacancies')
    op.create_index('ix_vacancies_pagination_created', 'vacancies', ['created_at', 'id'], unique=False)
    op.drop_index(op.f('ix_vacancies_pagination_published'), table_name='vacancies')
    op.create_index('ix_vacancies_pagination_published', 'vacancies', ['published_at', 'id'], unique=False)
    op.drop_constraint(op.f('vacancies_user_id_fkey'), 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'is_favorite')
    op.drop_column('vacancies', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('vacancies', sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('vacancies_user_id_fkey'), 'vacancies', 'users', ['user_id'], ['id'], onupdate='CASCADE')
    op.drop_index('ix_vacancies_pagination_published', table_name='vacancies')
    op.create_index(op.f('ix_vacancies_pagination_published'), 'vacancies', ['user_id', 'published_at', 'id'], unique=False)
    op.drop_index('ix_vacancies_pagination_created', table_name='vacancies')
    op.create_index(op.f('ix_vacancies_pagination_created'), 'vacancies', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_vacancies_is_favorite'), 'vacancies', ['is_favorite'], unique=False)
    op.drop_index('ix_user_vacancies_vacancy_id', table_name='user_vacancies')
    op.drop_index('ix_user_vacancies_user_id', table_name='user_vacancies')
    op.drop_index('ix_user_vacancies_favorite', table_name='user_vacancies')
    op.drop_table('user_vacancies')
    # ### end Alembic commands ###
