"""add search_vector to documents

Revision ID: 857fe542364f
Revises: d2765d6c291d
Create Date: 2026-03-09 18:22:58.872914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '857fe542364f'
down_revision: Union[str, Sequence[str], None] = 'd2765d6c291d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('russian', coalesce(title, '')), 'A') ||\n            setweight(to_tsvector('english', coalesce(title, '')), 'A') ||\n            setweight(to_tsvector('russian', coalesce(summary, '')), 'B') ||\n            setweight(to_tsvector('english', coalesce(summary, '')), 'B') ||\n            setweight(to_tsvector('russian', coalesce(content, '')), 'C') ||\n            setweight(to_tsvector('english', coalesce(content, '')), 'C')\n            ", persisted=True), nullable=True))
    op.create_index('ix_documents_search_vector', 'documents', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_search_vector', table_name='documents', postgresql_using='gin')
    op.drop_column('documents', 'search_vector')
    # ### end Alembic commands ###
