"""Add pagination indexes

Revision ID: 3909ac0cf04f
Revises: be3ec778db76
Create Date: 2026-01-17 14:30:56.548276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3909ac0cf04f'
down_revision: Union[str, Sequence[str], None] = 'be3ec778db76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_conversations_pagination', 'conversations', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_facts_pagination', 'facts', ['user_id', 'created_at', 'id'], unique=False)
    op.alter_column('invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('invites_code_key'), 'invites', type_='unique')
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=True)
    op.create_index('ix_messages_pagination', 'messages', ['conversation_id', 'timestamp', 'id'], unique=False)
    op.create_index('ix_prompts_pagination', 'prompts', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_vacancies_pagination_created', 'vacancies', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_vacancies_pagination_published', 'vacancies', ['user_id', 'published_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vacancies_pagination_published', table_name='vacancies')
    op.drop_index('ix_vacancies_pagination_created', table_name='vacancies')
    op.drop_index('ix_prompts_pagination', table_name='prompts')
    op.drop_index('ix_messages_pagination', table_name='messages')
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=False)
    op.create_unique_constraint(op.f('invites_code_key'), 'invites', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ix_facts_pagination', table_name='facts')
    op.drop_index('ix_conversations_pagination', table_name='conversations')
    # ### end Alembic commands ###
