"""update Fact model

Revision ID: b443eff556e9
Revises: 12cb275a7ea3
Create Date: 2026-02-09 18:36:43.706813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b443eff556e9'
down_revision: Union[str, Sequence[str], None] = '12cb275a7ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facts', sa.Column('mem0_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facts', 'mem0_id')
    # ### end Alembic commands ###
