"""(fix)Move is_active from Vacancy to UserVacancies

Revision ID: 6ec10bf7ad0a
Revises: 857fe542364f
Create Date: 2026-03-14 13:47:53.753433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec10bf7ad0a'
down_revision: Union[str, Sequence[str], None] = '857fe542364f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_vacancies', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.create_index(op.f('ix_user_vacancies_is_active'), 'user_vacancies', ['is_active'], unique=False)
    op.create_index('ix_user_vacancies_vacancy_id_is_active', 'user_vacancies', ['vacancy_id', 'is_active'], unique=False)
    op.drop_index(op.f('ix_vacancies_is_active'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_new_published'), table_name='vacancies')
    op.create_index('ix_vacancies_new_published', 'vacancies', ['published_at'], unique=False)
    op.drop_column('vacancies', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.drop_index('ix_vacancies_new_published', table_name='vacancies')
    op.create_index(op.f('ix_vacancies_new_published'), 'vacancies', ['published_at', 'is_active'], unique=False)
    op.create_index(op.f('ix_vacancies_is_active'), 'vacancies', ['is_active'], unique=False)
    op.drop_index('ix_user_vacancies_vacancy_id_is_active', table_name='user_vacancies')
    op.drop_index(op.f('ix_user_vacancies_is_active'), table_name='user_vacancies')
    op.drop_column('user_vacancies', 'is_active')
    # ### end Alembic commands ###
