"""add user role enum

Revision ID: 50dc154c0782
Revises: 374ab02fa641
Create Date: 2026-01-23 14:47:31.689513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50dc154c0782'
down_revision: Union[str, Sequence[str], None] = '374ab02fa641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем ENUM тип для ролей
    userrole_enum = sa.Enum('USER', 'ADMIN', 'MODERATOR', name='userrole', native_enum=False, length=20)
    userrole_enum.create(op.get_bind(), checkfirst=True)

    # Добавляем колонку role со значением по умолчанию 'user' для существующих записей
    op.add_column(
        'users',
        sa.Column('role', userrole_enum, nullable=False, server_default='user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
