"""add vacancies table

Revision ID: b67166532fd5
Revises: 38b613ee8c66
Create Date: 2026-01-08 20:47:33.135978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b67166532fd5'
down_revision: Union[str, Sequence[str], None] = '38b613ee8c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('hh_id', sa.String(length=32), nullable=False),
    sa.Column('query_request', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary_from', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salary_to', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('salary_gross', sa.Boolean(), nullable=True),
    sa.Column('experience_id', sa.String(length=20), nullable=True),
    sa.Column('area_id', sa.String(length=10), nullable=True),
    sa.Column('area_name', sa.String(length=100), nullable=True),
    sa.Column('schedule_id', sa.String(length=20), nullable=True),
    sa.Column('employment_id', sa.String(length=20), nullable=True),
    sa.Column('employer_id', sa.String(length=20), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('hh_url', sa.String(length=255), nullable=True),
    sa.Column('apply_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('published_at', sa.DateTime().with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(postgresql.TIMESTAMP(timezone=True), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_area_id'), 'vacancies', ['area_id'], unique=False)
    op.create_index(op.f('ix_vacancies_created_at'), 'vacancies', ['created_at'], unique=False)
    op.create_index(op.f('ix_vacancies_employer_id'), 'vacancies', ['employer_id'], unique=False)
    op.create_index(op.f('ix_vacancies_employment_id'), 'vacancies', ['employment_id'], unique=False)
    op.create_index(op.f('ix_vacancies_experience_id'), 'vacancies', ['experience_id'], unique=False)
    op.create_index(op.f('ix_vacancies_hh_id'), 'vacancies', ['hh_id'], unique=True)
    op.create_index(op.f('ix_vacancies_is_active'), 'vacancies', ['is_active'], unique=False)
    op.create_index(op.f('ix_vacancies_is_archived'), 'vacancies', ['is_archived'], unique=False)
    op.create_index('ix_vacancies_new_experience_schedule', 'vacancies', ['experience_id', 'schedule_id'], unique=False)
    op.create_index('ix_vacancies_new_published', 'vacancies', ['published_at', 'is_active'], unique=False)
    op.create_index('ix_vacancies_new_raw_data_gin', 'vacancies', ['raw_data'], unique=False, postgresql_using='gin')
    op.create_index('ix_vacancies_new_salary_area', 'vacancies', ['salary_from', 'area_id'], unique=False)
    op.create_index(op.f('ix_vacancies_published_at'), 'vacancies', ['published_at'], unique=False)
    op.create_index(op.f('ix_vacancies_query_request'), 'vacancies', ['query_request'], unique=False)
    op.create_index(op.f('ix_vacancies_salary_from'), 'vacancies', ['salary_from'], unique=False)
    op.create_index(op.f('ix_vacancies_salary_to'), 'vacancies', ['salary_to'], unique=False)
    op.create_index(op.f('ix_vacancies_schedule_id'), 'vacancies', ['schedule_id'], unique=False)
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('used_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('invites_pkey'))
    )
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=True)
    op.drop_index(op.f('ix_vacancies_schedule_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_salary_to'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_salary_from'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_query_request'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_published_at'), table_name='vacancies')
    op.drop_index('ix_vacancies_new_salary_area', table_name='vacancies')
    op.drop_index('ix_vacancies_new_raw_data_gin', table_name='vacancies', postgresql_using='gin')
    op.drop_index('ix_vacancies_new_published', table_name='vacancies')
    op.drop_index('ix_vacancies_new_experience_schedule', table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_is_archived'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_is_active'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_hh_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_experience_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_employment_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_employer_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_created_at'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_area_id'), table_name='vacancies')
    op.drop_table('vacancies')
    # ### end Alembic commands ###
