"""update documents table

Revision ID: d2765d6c291d
Revises: a63999dc73b6
Create Date: 2026-02-17 20:38:49.771302

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d2765d6c291d"
down_revision: str | Sequence[str] | None = "a63999dc73b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("summary_qdrant_id", sa.Uuid(), nullable=True))
    op.add_column("documents", sa.Column("summary_outdated", sa.Boolean(), nullable=False))
    op.drop_column("documents", "qdrant_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("qdrant_id", sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column("documents", "summary_outdated")
    op.drop_column("documents", "summary_qdrant_id")
    # ### end Alembic commands ###
