"""update VacancyAnalysis model

Revision ID: 374ab02fa641
Revises: eb36ad583fa0
Create Date: 2026-01-22 15:29:07.632571

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "374ab02fa641"
down_revision: str | Sequence[str] | None = "eb36ad583fa0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("vacancy_analyses", "model_used", existing_type=sa.VARCHAR(length=100), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("vacancy_analyses", "model_used", existing_type=sa.VARCHAR(length=100), nullable=False)
    # ### end Alembic commands ###
